clear all; close all; clc;


files = {...
    '/b/data/lem/M303/lemM303.rds.dxXmixacXdw.Cells.mat',...
    '/b/data/lem/M305/lemM305.rds.dxXmixacXdd.Cells.mat', ...
    '/b/data/lem/M306/lemM306.rds.dxXmixacXdd.Cells.mat', ...
    '/b/data/lem/M308/lemM308.rds.dxXmixacXdw1.Cells.mat', ... % Recall that we also have dw2, which is dw=0.15 deg
    '/b/data/jbe/M001/jbeM001.rds.dxXmixacXdd.Cells.mat', ...
    '/b/data/jbe/M002/jbeM002.rds.dxXmixacXdd.Cells.mat', ...
    '/b/data/jbe/M004/jbeM004.rds.dxXmixacXdd.Cells.mat', ...
    '/b/data/jbe/M006/jbeM006.rds.OpXmixacXdd.Cells.mat', ...
    '/b/data/jbe/M007/jbeM007.rds.dxXmixacXdd.Cells.mat', ...
    '/b/data/jbe/M008/jbeM008.rds.dxXmixacXdd.Cells.mat', ...
    '/b/data/lem/M309/lemM309.rds.dxXmixacXdd.Cells.mat', ...
    '/b/data/lem/M311/lemM311.rds.dxXmixacXdd.Cells.mat', ...
    '/b/data/lem/M312/lemM312.rds.dxXmixacXdd.Cells.mat'
     };

%files = {'/b/data/lem/M309/lemM309.rds.dxXmixacXdd.Cells.mat', ...
%    '/b/data/lem/M311/lemM311.rds.dxXmixacXdd.Cells.mat'};

outfile = 'CuratedCells5.mat';
for f = 1:length(files);
    fName = files{f};
    
    fprintf('Curating file %i\n', f);
    CurateCells(fName,'output',outfile);
end

load(outfile);
for dd = 1:length(Base);
    newBase(dd) = AddPenetrationInformation(Base(dd));
end
Base = newBase;

save(outfile,'Base');